# Generated by Django 5.2.4 on 2025-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_analisis_func_pacientes_analisis_funcional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisisfuncional',
            options={'verbose_name': 'Analisis funcional', 'verbose_name_plural': 'Analisis funcionales'},
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name': 'Antecedente', 'verbose_name_plural': 'Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='pacientes',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='analisis_funcional',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.analisisfuncional'),
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='antecedentes',
            field=models.ManyToManyField(blank=True, related_name='pacientes', to='pacientes.antecedentes'),
        ),
    ]
