# Generated by Django 5.2.4 on 2025-09-07 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidades',
            options={'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AlterModelOptions(
            name='puestos',
            options={'verbose_name': 'Puesto', 'verbose_name_plural': 'Puestos'},
        ),
        migrations.AddField(
            model_name='personal',
            name='especialidades',
            field=models.ManyToManyField(blank=True, related_name='personal', to='personal.especialidades'),
        ),
        migrations.AddField(
            model_name='personal',
            name='puestos',
            field=models.ManyToManyField(blank=True, related_name='personal', to='personal.puestos'),
        ),
    ]
