# Generated by Django 5.2.4 on 2025-09-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_alter_especialidades_options_alter_personal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='puestos',
            field=models.ManyToManyField(related_name='personal', to='personal.puestos'),
        ),
    ]
