# Generated by Django 5.2.4 on 2025-09-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_alter_personal_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='matricula',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
