# Generated by Django 5.2.4 on 2025-09-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_alter_personal_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='matricula',
            field=models.CharField(blank=True, default='-', max_length=255),
        ),
    ]
